spring.datasource.url=jdbc:h2:file:./dados/bancolp2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Recriar as tabelas apenas se houver mudanças estruturais (update minimiza dor de cabeca)
spring.jpa.hibernate.ddl-auto=update

# Ativar console do H2 para visualizarmos as tabelas pelo navegador se precisarmos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logar os comandos SQL pra debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
